services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 1
      MSSQL_SA_PASSWORD: YourStrong!Passw0rd
    restart: unless-stopped
    ports:
      - "1433:1433"
